apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 # Choose a free port in the range 30000-32767
    - protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 30500 # Choose another free port in the range 30000-32767
  type: NodePort

