apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 5Gi # Modify this to the required storage size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-storage
  # Add storage details specific to your storage provider (e.g., AWS, GCP, etc.)
  # For local storage (not recommended for production), use hostPath
  hostPath:
    path: /mnt/data/jenkins

