apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkins-storage
  resources:
    requests:
      storage: 5Gi # Request the same size as the PV or the required storage size

